import { createFileRoute, Link } from "@tanstack/react-router";
import { zodValidator, fallback } from "@tanstack/zod-adapter";
import { z } from "zod";
import { useMemo } from "react";
import { DashHeader } from "@/components/DashHeader";
import { AlertsFeed } from "@/components/AlertsFeed";
import { CITIES, generateAlerts } from "@/lib/heat-data";

const searchSchema = z.object({
  city: fallback(z.string(), "bengaluru").default("bengaluru"),
});

export const Route = createFileRoute("/alerts")({
  validateSearch: zodValidator(searchSchema),
  head: () => ({
    meta: [
      { title: "Alerts · ThermaGrid" },
      { name: "description", content: "National heat alert feed — wards crossing 45°C / 47°C / 49°C thresholds across India." },
    ],
  }),
  component: AlertsPage,
});

function AlertsPage() {
  const { city } = Route.useSearch();
  const all = useMemo(() => CITIES.flatMap((c) => generateAlerts(c)), []);
  const extreme = all.filter((a) => a.severity === "extreme").length;
  const high = all.filter((a) => a.severity === "high").length;
  const moderate = all.filter((a) => a.severity === "moderate").length;

  return (
    <div className="min-h-screen bg-background text-foreground">
      <DashHeader cityId={city} />
      <main className="mx-auto max-w-[1600px] space-y-5 px-6 py-6">
        <div>
          <h1 className="text-xl font-semibold">National Heat Alert Feed</h1>
          <p className="text-sm text-muted-foreground">
            Auto-generated by threshold engine (LST ≥ 45°C moderate · ≥ 47°C high · ≥ 49°C extreme).
          </p>
        </div>
        <div className="grid gap-4 md:grid-cols-3">
          <Tile label="Extreme" value={extreme} color="var(--heat-extreme)" />
          <Tile label="High" value={high} color="var(--heat-hot)" />
          <Tile label="Moderate" value={moderate} color="var(--heat-warm)" />
        </div>
        <AlertsFeed alerts={all.slice(0, 60)} onSelectWard={() => {}} />
        <div className="text-center">
          <Link to="/dashboard" search={{ city: city as never }} className="text-xs text-primary underline-offset-4 hover:underline">
            Return to mission control →
          </Link>
        </div>
      </main>
    </div>
  );
}

function Tile({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div className="glass-panel rounded-lg p-4">
      <div className="font-mono text-[10px] uppercase tracking-widest" style={{ color }}>{label}</div>
      <div className="mt-1 text-3xl font-semibold tabular-nums">{value}</div>
      <div className="font-mono text-[10px] text-muted-foreground">wards triggered</div>
    </div>
  );
}
