import { createFileRoute, Link } from "@tanstack/react-router";
import { zodValidator, fallback } from "@tanstack/zod-adapter";
import { z } from "zod";
import { useMemo } from "react";
import { DashHeader } from "@/components/DashHeader";
import { AppBackground } from "@/components/AppBackground";
import { AlertsFeed } from "@/components/AlertsFeed";
import { CITIES, generateAlerts } from "@/lib/heat-data";
import { AlertTriangle, Bell, ArrowLeft } from "lucide-react";

const searchSchema = z.object({
  city: fallback(z.string(), "bengaluru").default("bengaluru"),
});

export const Route = createFileRoute("/alerts")({
  validateSearch: zodValidator(searchSchema),
  head: () => ({
    meta: [
      { title: "Alerts · ThermaGrid" },
      { name: "description", content: "National heat alert feed — wards crossing 45°C / 47°C / 49°C thresholds across India." },
    ],
  }),
  component: AlertsPage,
});

function AlertsPage() {
  const { city } = Route.useSearch();
  const all = useMemo(() => CITIES.flatMap((c) => generateAlerts(c)), []);
  const extreme = all.filter((a) => a.severity === "extreme").length;
  const high = all.filter((a) => a.severity === "high").length;
  const moderate = all.filter((a) => a.severity === "moderate").length;

  return (
    <div className="relative min-h-screen overflow-x-hidden bg-background text-foreground">
      <AppBackground />
      <DashHeader cityId={city} />
      <main className="mx-auto max-w-[1600px] space-y-4 px-4 py-4 sm:space-y-6 sm:px-6 sm:py-6">
        <div className="space-panel rounded-2xl p-5">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-[var(--heat-extreme)]/12 p-2.5 text-[var(--heat-extreme)]" style={{ boxShadow: "0 0 12px color-mix(in oklch, var(--heat-extreme) 20%, transparent)" }}>
              <Bell className="h-5 w-5" />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-tight text-gradient-space">National Heat Alert Feed</h1>
              <p className="text-xs text-muted-foreground mt-1">
                Auto-generated by threshold engine (LST ≥ 45°C moderate · ≥ 47°C high · ≥ 49°C extreme).
              </p>
            </div>
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-3">
          <Tile label="Extreme" value={extreme} color="var(--heat-extreme)" bg="bg-[var(--heat-extreme)]/12" />
          <Tile label="High" value={high} color="var(--heat-hot)" bg="bg-[var(--heat-hot)]/12" />
          <Tile label="Moderate" value={moderate} color="var(--heat-warm)" bg="bg-[var(--heat-warm)]/12" />
        </div>

        <AlertsFeed alerts={all.slice(0, 60)} onSelectWard={() => {}} />

        <div className="text-center pt-2">
          <Link
            to="/dashboard"
            search={{ city: city as never }}
            className="inline-flex items-center gap-2 rounded-xl border border-primary/20 bg-primary/8 px-4 py-2 font-mono text-xs font-bold uppercase tracking-wider text-primary transition-all hover:bg-primary/15"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Return to mission control
          </Link>
        </div>
      </main>
    </div>
  );
}

function Tile({ label, value, color, bg }: { label: string; value: number; color: string; bg: string }) {
  return (
    <div className="space-panel rounded-2xl p-5 group transition-all hover:shadow-[0_0_15px_var(--primary)/10]">
      <div className="font-mono text-[10px] uppercase tracking-widest font-bold" style={{ color }}>{label}</div>
      <div className="mt-2 text-3xl font-bold tabular-nums tracking-tight">{value}</div>
      <div className="mt-2 inline-flex items-center gap-1.5 rounded-lg border border-primary/8 bg-card/40 px-2 py-0.5 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
        wards triggered
      </div>
    </div>
  );
}
